apiVersion: v1
kind: Service
metadata:
  name: nginx-tv-svc
spec:
  selector:
    app: nginx-tv-svc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  externalTrafficPolicy: Cluster