apiVersion: v1
kind: Service
metadata:
  name: nginx-tv-svc
  # annotations:
  #     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: nginx-tv-svc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP