apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-tv-app
  template:
    metadata:
      labels:
        app: spring-tv-app
    spec:
      nodeSelector:
        my-label-key: aks-defaultpool-63129824-vmss000001
      containers:
        - name: spring-app
          image: acrprod0327.azurecr.io/production/spring-tv-app
          ports:
          - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev